version: "3.9"

services:
  llm-app:
    build: .
    container_name: llm_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root s3://dummy/
      --host 0.0.0.0
      --port 5000

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - llm-app
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  drift-exporter:
    build:
      context: ./monitoring
    container_name: drift_exporter
    depends_on:
      - prometheus

