name: GitHub Extractor Tests

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r week3/project/github_extractor/requirements.txt
          pip install pytest pytest-cov requests

      - name: Run only GitHub Extractor tests
        working-directory: week3/project/github_extractor
        run: pytest -v --maxfail=1 --disable-warnings
