name: GitHub Extractor Tests

on:
  push:
    paths:
      - "week3/project/github_extractor/**"
  pull_request:
    paths:
      - "week3/project/github_extractor/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r week3/project/github_extractor/requirements.txt

      - name: Run only GitHub Extractor tests
        run: |
          cd week3/project/github_extractor
          pytest -v --maxfail=1 --disable-warnings \
            --ignore=../weather_tool \
            --ignore=../currency_convertor